
# 数据库配置
sqlite:
  # 是否区分玩家名称的大小写, 仅可在创建数据库时启用, 影响所有需要查询名称的功能
  # 启用后, 使用指令可能会变得麻烦
  nameCaseSensitive: false


# 连接到其他插件
hook:
  # 离线登录插件
  AuthMe: true


# 白名单配置
# 白名单验证流程与配置的顺序相同
whitelist:

  # 简易的 ip 黑名单. 在这里添加正则表达式, 匹配的ip不允许加入服务器 (也不允许使用参观账户
  # 使用 /wl reload 重载配置即可应用
  ipBlacklist: [ ]
  #    - '^192\.168\.100\..+$'
  #    - '^fe80::1234:.+$' # IPv6 没有方括号
  ipBlacklistMsg: '§6IpacEL §f> §b您已被列入黑名单: §a%playerName%' # var: %ip%

  # 玩家名称字符检查
  # 名称长度为 3 到 16 字符, 允许包含 Geyser 的 "." 前缀
  playerNameRule: '^(?:\.?[a-zA-Z0-9_]{3,16})$'
  playerNameRuleMsg: '§6IpacEL §f> §a名称中包含不支持的字符: §b%playerName%'

  # 服务器启动完毕后需要等待多长时间才允许玩家加入 (毫秒
  lateJoinTime: 4000 # 4秒
  lateJoinTimeMsg: '§6IpacEL §f> §b服务器正在启动'

  # 防止玩家短时间内重复加入退出 (毫秒
  repeatJoinInterval: 1200 # 1.2秒
  repeatJoinIntervalMsg: '§6IpacEL §f> §b连接受限, 请稍后重试'

  # 启用最大玩家数量限制
  # 拥有 IpacWhitelist.maxPlayers.bypass 权限的玩家可绕过最大人数限制
  maxPlayers: true
  maxPlayersIncludesVisit: true  # 参观账户是否包含在玩家总数中
  maxPlayersMsg: '§6IpacEL §f> §b服务器已满'

  # 防止名称相同, 但 UUID 不同的玩家加入
  preventNameDuplication: true
  preventNameDuplicationMsg: '§6IpacEL §f> §b存在名称重复的玩家, 请联系管理员检查'


  # 以下根据玩家当前的类型对配置分类

  # 玩家不在白名单中
  NOT:
    # 使用参观账户, 允许玩家参观服务器
    visitEnable: true
    # 否则不允许加入, 发出以下消息
    notMsg: '§6IpacEL §f> §b您不在白名单中或已失效, 请联系管理员恢复§7: §a%playerName%'

    # 注意! 这里可能缺少 UUID 或 NAME, 这取决于使用 `/wl add` 指令时的输入内容
    onWhitelistAddEvent: [ ] # 玩家被添加到白名单

  # 参观账户
  VISIT:
    # 参观账户的名称字符检查
    playerNameRule: '^(?:\.?[a-zA-Z0-9_]{3,16})$'
    playerNameRuleMsg: '§6IpacEL §f> §a名称中包含不支持的字符: §b%playerName%'

    # 同时允许多少参观账户加入服务器
    maxPlayers: 10
    maxPlayersMsg: '§6IpacEL §f> §b参观队列已满'

    # [AuthMe] 自动注册登录参观账户
    AuthMePlugin:
      # 为参观账户自动注册和登录, 相当于 `/authme register <playerName> <password>` 和 `/authme forcelogin <playerName>`, 但不会踢出玩家
      autoRegisterAndLogin: true
      # 第一次注册后无需登录, 如果 AuthMe 启用了此功能, 这里也需要启用. 建议启用
      noLoginAfterRegister: true
      # 需要在这里填写一个复杂的密码, 只要满足 AuthMe 的密码规则即可
      autoRegisterPassword: 'complexPassword'

    # [事件程序] 以 "on" 开头, "Event" 结尾的配置均可使用此模板
    # kick    = 同步踢出玩家, 并显示消息
    # cmd     = 同步运行控制台命令
    # msg     = 发送消息给这个玩家
    # msgBroadcast = 广播消息给所有玩家
    # msgExclude   = 广播消息给其他所有玩家
    # [变量] 对于操作数据的功能尽量使用 UUID 而非 NAME, 防止因为名称冲突而影响数据
    # %playerUUID%  = 玩家 UUID 36 位字符串
    # %playerName%  = 玩家名称, 区分大小写
    onNewPlayerLoginEvent: # 参观账户第一次登录服务器
      cmd:
        - 'lp user %playerUUID% parent add visit' # 将玩家添加到 visit 权限组

    onPlayerLoginEvent: [ ] # 参观账户每次登录服务器

    onPlayerJoinEvent: # 参观账户加入服务器
      cmd:
        - 'gamemode spectator %playerName%' # 将玩家设置为观察模式
      msg:
        - '§6IpacEL §f> §a您正在使用参观账户=w='
#        - '§6IpacEL §f> §b如需加入, 请访问我们的网站: §ahttps://ipacel.cc/'
      msgExclude:
        - '§6IpacEL §f> §a%playerName% §b使用参观账户加入游戏'

    onPlayerQuitEvent: # 参观账户退出服务器
      msgBroadcast:
        - '§6IpacEL §f> §a%playerName% §b跑了'

    onWhitelistAddEvent: # 参观账户被添加到白名单
      kick:
        - '§6IpacEL §f> §a您已添加到白名单, 请重新登录服务器'
      cmd:
        - 'lp user %playerUUID% parent remove visit' # 将玩家移出 visit 用户组
        - 'authme unregister %playerName%' # 取消注册玩家

  # 被添加到白名单中的参观账户, 需要通过此流程进行数据转换
  # 之后在 WHITE 分类中继续运行
  VISIT_CONVERT:
    onPlayerLoginEvent: [ ] # 需要转换账户类型的玩家登录

    onPlayerJoinEvent: # 需要转换账户类型的玩家加入
      cmd:
        - 'spawn %playerName%' # 传送到重生点
        - 'gamemode survival %playerName%' # 将玩家设置为生存模式

    # <- 现在玩家正式添加到白名单, 将继续运行 WHITE 中的配置

  # 白名单中的玩家
  WHITE:
    onPlayerLoginEvent: [ ] # 玩家登录服务器

    onPlayerJoinEvent: # 玩家加入服务器
      msgBroadcast:
        - '§6IpacEL §f> §a%playerName% §b加入游戏'

    onAuthMeLoginEvent: # 玩家通过 AuthMe 登录成功
      msgBroadcast:
        - '§6IpacEL §f> §a%playerName% §b登录成功'

    onAuthMeFailedLoginEvent: # 玩家通过 AuthMe 登录失败
      msgBroadcast:
        - '§6IpacEL §f> §a%playerName% §b断开连接: §7密码错误'

    onPlayerQuitEvent: # 玩家退出服务器
      msgBroadcast:
        - '§6IpacEL §f> §a%playerName% §b跑了'

    onAuthMeLogoutEvent: [ ] # 玩家通过 AuthMe 注销

    onWhitelistDelEvent: # 白名单被移除
      kick:
        - '§6IpacEL §f> §b您已被移出白名单'


  # 被封禁的账户
  BAN:
    # 被封禁账户登录时的消息
    kickMsg: '§6IpacEL §f> §a您已被列入黑名单: §b%playerName%'

    onWhitelistBanEvent: # 任何玩家被添加到黑名单
      kick:
        - '§6IpacEL §f> §b您已被添加到黑名单'

    onWhitelistUnbanEvent: [ ] # 玩家从黑名单中移出

    onPlayerLoginEvent: [ ] # 玩家登录服务器


# 指令配置
# 如无必要, 请勿修改这部分消息, 防止信息显示错误
command:

  add:
    title:   '§6IpacEL §f> §a添加到白名单[§b%var%§a]:'
    isBan:   '  - §a%playerName%§f[§7%playerUUID%§f] §b已在黑名单中, 不可操作'
    isExist: '  - §a%playerName%§f[§7%playerUUID%§f] §b已在白名单中'
    isVisit: '  - §a%playerName%§f[§7%playerUUID%§f] §a已从参观账户中重置'
    finish:  '  - §a%playerName%§f[§7%playerUUID%§f] §a已完成'

  del:
    title:   '§6IpacEL §f> §b从白名单移出[§a%var%§b]:'
    isEmpty: '  - §a%playerName%§f[§7%playerUUID%§f] §b不存在'
    isMulti: '  - §a%playerName%§f[§7%playerUUID%§f] §b存在重复数据'
    isBan:   '  - §a%playerName%§f[§7%playerUUID%§f] §b已在黑名单中, 不可操作'
    finish:  '  - §a%playerName%§f[§7%playerUUID%§f] §a已完成'

  ban:
    title:   '§6IpacEL §f> §b添加到黑名单[§a%var%§b]:'
    isBan:   '  - §a%playerName%§f[§7%playerUUID%§f] §b已在黑名单中'
    isMulti: '  - §a%playerName%§f[§7%playerUUID%§f] §b存在重复数据'
    finish:  '  - §a%playerName%§f[§7%playerUUID%§f] §a已完成'

  unban:
    title:   '§6IpacEL §f> §a从黑名单移出[§b%var%§a]:'
    isEmpty: '  - §a%playerName%§f[§7%playerUUID%§f] §b不存在'
    isMulti: '  - §a%playerName%§f[§7%playerUUID%§f] §b存在重复数据'
    isUnban: '  - §a%playerName%§f[§7%playerUUID%§f] §b不在黑名单中'
    finish:  '  - §a%playerName%§f[§7%playerUUID%§f] §a已完成'

  info:
    title:   '§6IpacEL §f> §b查询玩家信息[§a%var%§b]:'
    isEmpty: '  - §a%playerName%§f[§7%playerUUID%§f] §b不存在'
    finish: >
      §f  - §a%playerName%§f[§7%playerUUID%§f]: [§bID: §6%id%§f]
            - §bTYPE: §6%type%
            - §bBAN: §6%ban%
            - §bTIME: §6%time%

  list:
    title:   '§6IpacEL §f> §b查询玩家信息[§a%type%§b]:'
    noData:  '  - §b这个标签下没有任何数据'
    isEmpty: '  - §a%playerName%§f[§7%playerUUID%§f] §b不存在'
    finish:  '  - [§6%time%§f] {§bID§f: §6%id%§f, §bType§f: "§6%type%§f", §bBan§f: "§6%ban%§f", §bUUID§f: "§a%playerUUID%§f", §bName§f: "§a%playerName%§f", §bTime§f: §6%timeLong%§f}'

  # 用于清理玩家数据的功能, 请提前在本地测试完毕后再启用
  # [注意]
  # 在使用清理功能前请检查是否存在名称重复的数据: /wl list NAME_CONFLICT
  clear:
    enable: false
    title:  '§6IpacEL §f> §b运行数据清理[§a%type%:%var%§b]:'
    isMiss: '  - §a%playerName%§f[§7%playerUUID%§f] §b缺少必要的玩家信息'
    online: '  - §a%playerName%§f[§7%playerUUID%§f] §b玩家在线'

    # 只处理离线超过指定时间的账户, 防止清除后被保存 (秒
    delTime: 43200 # 12小时. 它必须大于数据缓存时间
    delTimeMsg: '  - §a%playerName%§f[§7%playerUUID%§f] §b未达到可删除的时间'

    # 不应该处理存在重复名称的数据
    repeat: '  - §a%playerName%§f[§7%playerUUID%§f] §b存在重复的名称'

    # [注意]
    # 清理数据的配置尽量使用 playerUUID, 而非 playerName, 防止因为重名而误删数据

    # 运行指令
    runCommand:
      - 'lp user %playerUUID% clear'      # 清除玩家权限
      - 'authme unregister %playerName%'  # 取消注册玩家

    # 运行指令和清除文件之间的间隔 (毫秒
    delayStep: 270

    # 清除文件
    # %worldPath% = 所有地图的根目录
    # %worldName% = 所有地图的名称
    # %playerUUID32%  = 32位, 不带连字符的 UUID
    clearFile:
      # 清理所有地图下的存档
      - '%worldPath%/playerdata/%playerUUID%.dat'
      - '%worldPath%/playerdata/%playerUUID%.dat_old'
      - '%worldPath%/advancements/%playerUUID%.json'
      - '%worldPath%/stats/%playerUUID%.json'
      # 清理 Essentials 插件下的玩家数据
      - 'plugins/Essentials/userdata/%playerUUID%.yml'
      # 清理粘液科技文件
      - 'data-storage/Slimefun/waypoints/%playerUUID%.yml'

    # 循环之间的时间间隔 (毫秒
    delayLoop: 727

    ing:     '  - [%var%:%id%] §a%playerName%§f[§7%playerUUID%§f] §a已完成'
    finish:  '§6IpacEL §f> §a数据清理运行完毕'

  # 从旧版本 IpacWhitelist 导入数据的功能, 默认关闭防止误触
  importData:
    enable: false
    # 从文本文件中导入数据, 每行一条数据
    file: 'Data.txt'
    # 用于匹配数据的正则, 这里是 v3 版本的 List 指令导出格式. 使用指令: /wl list * ALL
    regExp: '\{ID: \d+, Type: "([^"]+)", Ban: "([^"]+)", UUID: "([^"]+)", Name: "([^"]+)", Time: (-?\d+)\}$'
    # 不同数据所在的匹配组 ID
    TYPE: 1
    BAN: 2
    UUID: 3
    NAME: 4
    TIME: 5


# 其他消息
message:
  noEnable: '§6IpacEL §f> §b功能未启用'
  noPermission: '§6IpacEL §f> §b没有权限'
  parameterErr: '§6IpacEL §f> §a参数不可识别或未通过检查: §b%var%'
  playerLoginErr: '§6IpacEL §f> §b出现未知的错误, 请联系管理员检查'
