# 数据库
sql:
  # sqlite 和 h2 为单文件数据库, 无需修改其他数据库配置
  db: mysql
  # mysql: com.mysql.jdbc.Driver
  # h2: org.h2.Driver
  jdbc_driver: 'com.mysql.jdbc.Driver' # 留空则不使用

  host: localhost
  port: 3306
  user: root
  password: password
  database: IpacWhitelist
  table: player


# 消息
message:
  # %player% = 玩家名称
  add-ok: '§6IpacEL §f> §b%player% §a已添加到白名单'
  del-ok: '§6IpacEL §f> §a%player% §b已从白名单移出'
  not: '§6IpacEL §f> §b您不在白名单中§7: §a%player%'

  reload: '§6IpacEL §f> IpacWhitelist重载完成'

  err-name-length: '§6IpacEL §f> §b名称长度异常'
  err-uuid-length: '§6IpacEL §f> §bUUID长度异常'
  err-sql: '§6IpacEL §f> §b内部错误'
  err-sql-player-join: '§6IpacEL §f> §a发生内部错误, 请稍后重试或联系管理员解决'
