name: IpacWhitelist
authors: [ ApliNi ]
version: '${project.version}'
main: aplini.ipacwhitelist.IpacWhitelist
api-version: 1.19

softdepend:
  - AuthMe
  - Geyser-Spigot
  - PlaceholderAPI

commands:
  wl:
    description: 白名单指令
    usage: /<command>
    aliases: [ ipacwhitelist ]

permissions:

  IpacWhitelist.maxPlayers.bypass:
    description: '绕过最大人数限制'
    default: op

  IpacWhitelist.cmd:
    description: '使用指令和指令补全'
    default: op

  IpacWhitelist.cmd.reload:
    description: '使用 /wl reload 指令'
    default: op

  IpacWhitelist.cmd.add:
    description: '使用 /wl add 指令'
    default: op

  IpacWhitelist.cmd.del:
    description: '使用 /wl del 指令'
    default: op

  IpacWhitelist.cmd.ban:
    description: '使用 /wl ban 指令'
    default: op

  IpacWhitelist.cmd.unban:
    description: '使用 /wl unban 指令'
    default: op

  IpacWhitelist.cmd.search:
    description: '使用 /wl search 指令'
    default: op

  IpacWhitelist.cmd.info:
    description: '使用 /wl info 指令'
    default: op

  IpacWhitelist.cmd.list:
    description: '使用 /wl list 指令'
    default: op

  IpacWhitelist.cmd.clear:
    description: '使用 /wl clear 指令'
    default: op

  IpacWhitelist.cmd.importData:
    description: '使用 /wl importData 指令'
    default: op
