name: IpacWhitelist
version: '${project.version}'
main: aplini.ipacwhitelist.IpacWhitelist
api-version: 1.19

softdepend:
  - AuthMe

commands:
  wl:
    description: 白名单指令
    usage: /<command>
    aliases: [ipacwhitelist]

permissions:

  IpacWhitelist.maxPlayers.bypass:
    description: '绕过最大人数限制'
    default: op

  IpacWhitelist.cmd.reload:
    description: '使用 /wl reload 指令'
    default: op

  IpacWhitelist.cmd.add:
    description: '使用 /wl add 指令'
    default: op

  IpacWhitelist.cmd.del:
    description: '使用 /wl del 指令'
    default: op

  IpacWhitelist.cmd.ban:
    description: '使用 /wl ban 指令'
    default: op

  IpacWhitelist.cmd.unban:
    description: '使用 /wl unban 指令'
    default: op

  IpacWhitelist.cmd.info:
    description: '使用 /wl info 指令'
    default: op

  IpacWhitelist.cmd.list:
    description: '使用 /wl list 指令'
    default: op

  IpacWhitelist.cmd.clean:
    description: '使用 /wl clean 指令'
    default: op
