name: IpacWhitelist
version: '${project.version}'
main: aplini.ipacwhitelist.IpacWhitelist
api-version: 1.19

softdepend:
  - AuthMe

commands:
  wl:
    description: 白名单
    usage: /<command>
    aliases: [ipacwhitelist]

permissions:
  IpacWhitelist.command.reload:
    description: '使用 /wl reload 指令'
    default: op

  IpacWhitelist.command.add:
    description: '使用 /wl add 指令'
    default: op

  IpacWhitelist.command.del:
    description: '使用 /wl del 指令'
    default: op

  IpacWhitelist.command.ban:
    description: '使用 /wl ban 指令'
    default: op

  IpacWhitelist.command.unban:
    description: '使用 /wl unban 指令'
    default: op

  IpacWhitelist.command.info:
    description: '使用 /wl info 指令'
    default: op

  IpacWhitelist.command.list:
    description: '使用 /wl list 指令'
    default: op

  IpacWhitelist.command.clean_visit:
    description: '使用 /wl clean_visit 指令'
    default: op

  IpacWhitelist.command.clean:
    description: '使用 /wl clean 指令'
    default: op
